name: Feature request
description: Suggest something
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What is awkward today
      description: Describe the situation, not the solution.
    validations:
      required: true

  - type: textarea
    id: idea
    attributes:
      label: What you have in mind
    validations:
      required: false
